#!/bin/sh
set -eo pipefail

if [ "$#" -ne 2 ]; then
  echo "USAGE: $0 <clone url> <push url>"
  exit 1
fi

# Find the name of the directories
p=`echo "${1}" | sed -r -e 's#.*(://|@)(.*)/[^/]*(\.git|$)#\2#g' -e 's#:#/#g'`
r=`echo "${1}" | sed -r -e 's#.*/([^/]*)(\.git|$)#\1#g'`

mkdir -p "/data/$p"
cd "/data/$p"

if [ ! -d "${r}.git" ]; then
  git clone --mirror "$1"
  cd "${r}.git"
  git config remote.origin.pushurl "$2"
else
  cd "${r}.git"
fi

git fetch --force
git fetch --force --tags
git push --mirror
